(defun auto-indent/forward-char ()
  (interactive)
  (forward-char)
  (indent-according-to-mode))

(defun auto-indent/beginning-of-line ()
  (interactive)
  (beginning-of-line)
  (indent-according-to-mode))

(defun auto-indent/point-at-beginning-of-line-text ()
  (<= (point)
      (save-excursion
        (auto-indent/beginning-of-line)
        (point))))

(defun auto-indent/backward-char ()
  (interactive)
  (if (auto-indent/point-at-beginning-of-line-text)
      (progn (beginning-of-line)
             (backward-char)
             (indent-according-to-mode))
    (backward-char)))

(defun auto-indent/delete-char ()
  (interactive)
  (if (= (point) (line-end-position))
      (progn
        (delete-region (point)
                       (progn (next-line)
                              (auto-indent/beginning-of-line)
                              (point)))
        (indent-according-to-mode))
    (delete-char 1)))

(defun auto-indent/backward-delete-char ()
  (interactive)
  (if (auto-indent/point-at-beginning-of-line-text)
      (progn
        (delete-region (point)
                       (progn (previous-line)
                              (end-of-line)
                              (point)))
        (indent-according-to-mode))
        (backward-delete-char-untabify 1)))

(defun auto-indent/next-line ()
  (interactive)
  (setq this-command 'next-line)
  (next-line)
  (indent-according-to-mode))

(defun auto-indent/previous-line ()
  (interactive)
  (setq this-command 'previous-line)
  (previous-line)
  (indent-according-to-mode))

(defun auto-indent-hook ()
  (interactive)
  (local-set-key [right] 'auto-indent/forward-char)
  (local-set-key [left] 'auto-indent/backward-char)
  (local-set-key [return] 'newline-and-indent)
  (local-set-key [delete] 'auto-indent/delete-char)
  (local-set-key [backspace] 'auto-indent/backward-delete-char)
  (local-set-key [home] 'auto-indent/beginning-of-line)
  (local-set-key [up] 'auto-indent/previous-line)
  (local-set-key [down] 'auto-indent/next-line))

(add-hook 'c-mode-hook 'auto-indent-hook)
(add-hook 'emacs-lisp-mode-hook 'auto-indent-hook)
