(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(align-c++-modes (quote (c++-mode c-mode java-mode js-mode)))
 '(auto-indent-delete-line-char-remove-extra-spaces t)
 '(auto-indent-delete-trailing-whitespace-on-save-file t)
 '(auto-indent-global-mode t nil (auto-indent-mode))
 '(blink-matching-paren nil)
 '(campfire-domain "pennyace.campfirenow.com")
 '(campfire-ssl t)
 '(compilation-read-command nil)
 '(geiser-mode-autodoc-p nil)
 '(hippie-expand-try-functions-list (quote (try-complete-file-name-partially try-complete-file-name try-expand-all-abbrevs try-expand-dabbrev try-expand-dabbrev-all-buffers try-expand-dabbrev-from-kill try-expand-line try-complete-lisp-symbol-partially try-complete-lisp-symbol)))
 '(initial-scratch-message nil)
 '(js-indent-level 2)
 '(mac-command-modifier (quote alt))
 '(mac-option-modifier (quote meta))
 '(mouse-wheel-progressive-speed nil)
 '(mouse-wheel-scroll-amount (quote (6 ((shift) . 1) ((control)))))
 '(notmuch-message-headers-visible nil)
 '(notmuch-search-oldest-first nil)
 '(notmuch-show-elide-same-subject t)
 '(notmuch-show-logo nil)
 '(org-agenda-files (quote ("~/research/stacked/README.org" "~/code/musicvis/README.org" "~/code/bibgrep/README.org" "~/edu/ee/README.org" "~/research/papers/waveform/README.org" "~/blog/README.org" "~/edu/math/comb/README.org" "~/misc/notes.org" "~/research/README.org" "~/code/arch.org" "~/code/README.org" "~/work/README.org" "~/edu/art/README.org" "~/README.org" "~/edu/school/README.org" "~/.emacs.d/README.org" "~/edu/math/calc/README.org" "~/misc/books.org" "~/misc/house.org" "~/edu/plt/README.org" "~/edu/music/README.org")))
 '(org-agenda-todo-ignore-deadlines (quote all))
 '(org-agenda-todo-ignore-scheduled (quote all))
 '(org-babel-load-languages (quote ((haskell . t) (ruby . t) (emacs-lisp . t) (C . t) (sh . t))))
 '(org-clock-into-drawer 2)
 '(org-confirm-babel-evaluate nil)
 '(org-disputed-keys (quote (([(shift up)] . [(meta p)]) ([(shift down)] . [(meta n)]) ([(shift left)] . [(meta -)]) ([(shift right)] . [(meta +)]) ([(control shift right)] . [(meta shift +)]) ([(control shift left)] . [(meta shift -)]) ([(meta left)] . [(shift meta left)]) ([(meta right)] . [(shift meta right)]) ([(meta down)] . [(shift meta down)]) ([(meta up)] . [(shift meta up)]) ((kbd "C-'")))))
 '(org-export-creator-info nil)
 '(org-export-html-validation-link "")
 '(org-link-to-org-use-id (quote use-existing))
 '(org-mobile-force-id-on-agenda-items nil)
 '(org-refile-targets (quote ((org-agenda-files :level . 1))))
 '(org-refile-use-outline-path (quote full-file-path))
 '(org-replace-disputed-keys t)
 '(org-startup-indented t)
 '(org-use-speed-commands t)
 '(python-indent 3)
 '(rcirc-authinfo (quote (("irc.freenode.net" nickserv "jtxx000" "fgcrl"))))
 '(require-final-newline t)
 '(revert-without-query (quote (".*")))
 '(rst-adornment-faces-alist (quote ((t . font-lock-keyword-face) (nil . font-lock-keyword-face) (1 . font-lock-function-name-face) (2 . font-lock-function-name-face) (3 . font-lock-function-name-face) (4 . font-lock-function-name-face) (5 . font-lock-function-name-face) (6 . font-lock-function-name-face))))
 '(scroll-bar-mode nil)
 '(standard-indent 2)
 '(tab-width 4)
 '(transient-mark-mode t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(org-date ((((class color) (background dark)) (:foreground "#729fcf" :underline t)))))
