(add-to-list 'load-path "~/.emacs.d")
(add-to-list 'load-path "~/.emacs.d/vendor")

(server-start)

(load-library "visual")
(load-library "util")
(load-library "keys")
(load-library "misc")
(load-library "show-paren-offscreen")
(load-library "auto-indent")
(load-library "site-c-esque")
(load-library "time-mode")
(load-library "notes-mode")

(load "haskell-mode-2.4/haskell-site-file.el")
(autoload 'cycle-buffer "cycle-buffer" "Cycle forward." t)
(require 'anything-config)
(load-library "site-yasnippet")
(load-library "site-rst")
(load-library "site-io")
(load-library "site-python")
(load-library "site-cpp")
(load-library "site-lisp")
(require 'haml-mode)
(require 'paredit)

(autoload 'd-mode "d-mode" "Major mode for editing D code." t)
(add-to-list 'auto-mode-alist '("\\.d[i]?\\'" . d-mode))
(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.rb\\'" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\work-hours\\'" . time-mode))
