(set-kbd-keys global
  ("C-p"         . cycle-buffer)
  ("C-S-p"       . cycle-buffer-backward)
  ("C-z"         . kill-current-buffer)
  ("C-n"         . save-buffer)
  ("C-f"         . find-file)
  ("C-b"         . switch-to-buffer)
  ("M-1"         . delete-other-windows)
  ("M-g"         . goto-line)
  ("C-'"         . duplicate-line)
  ("C-<return>"  . newline-under)
  ("C-\\"        . newline-over)
  ("<f8>"        . undo)
  ("C-("         . kmacro-start-macro)
  ("C-)"         . kmacro-end-macro)
  ("C-*"         . kmacro-end-and-call-macro)
  ("M-@"         . kill-ring-save-buffer)
  ("M-2"         . split-window-vertically)
  ("M-3"         . split-window-horizontally)
  ("C-<tab>"     . hippie-expand)
  ("C-e"         . mark-paragraph)
  ("C-v"         . kill-ring-save-line)
  ("M-<right>"   . windmove-right)
  ("M-<left>"    . windmove-left)
  ("M-<up>"      . windmove-up)
  ("M-<down>"    . windmove-down)
  ("M-S-<left>"  . winner-undo)
  ("M-S-<right>" . winner-redo)
  ("C-c C-a"     . align-current)
  ("M-$"         . calc)
  ("C-$"         . quick-calc)
  ("C-S-b"       . switch-to-buffer-other-window)
  ("C-l"         . recenter-no-erase)
  ("C-S-c"       . compile)
  ("C-`"         . next-error)

  ("C-+" . increment-word)

  ("S-<up>"        . backward-up-list)
  ("C-S-<up>"      . up-list)
  ("S-<down>"      . down-list)
  ("C-S-<down>"    . backward-down-list)
  ("C-S-<left>"    . backward-to-previous-sexp)
  ("C-S-<right>"   . forward-to-next-sexp)
  ("S-<left>"      . paredit-backward)
  ("S-<right>"     . paredit-forward)
  ("S-<delete>"    . kill-sexp)
  ("S-<backspace>" . backward-kill-sexp)
  ("C-S-t"         . transpose-sexps)
  ("M-9"           . insert-parentheses)
  ("M-0"           . move-past-close-and-reindent))

(if (not (system-is-osx))
    (set-kbd-keys global ("M-<backspace>" . kill-entire-line)))

(if (system-is-osx)
    (progn
      (set-kbd-keys global
        ("M-<up>"        . backward-paragraph)
        ("M-<down>"      . forward-paragraph)
        ("A-w"           . kill-this-buffer)
        ("A-f"           . find-file)
        ("A-q"           . kill-emacs)
        ("A-<up>"        . beginning-of-buffer)
        ("A-<down>"      . end-of-buffer)
        ("A-<left>"      . beginning-of-line)
        ("A-<right>"     . end-of-line)
        ("A-<backspace>" . kill-entire-line)
        ("A-s"           . save-buffer))))
