(defun insert-brackets ()
  (interactive)
  (if (and (not (bobp))
               (or (equal 'font-lock-comment-face
                          (get-char-property (1- (point))
                                             'face))
                   (equal 'font-lock-string-face
                          (get-char-property (1- (point))
                                             'face))))
      (insert "{")
    (delete-region (point)
                   (save-excursion
                     (search-backward-regexp "[^ \t\n]")
                     (forward-char)
                     (point)))
    (insert " {")
    (newline)
    (newline-and-indent)
    (insert "}")
    (indent-according-to-mode)
    (previous-line)
    (indent-according-to-mode)))

(defun c-esque/end-of-line ()
  (interactive)
  (end-of-line)
  (and (/= (point) 1)
       (string= (buffer-substring (point) (1- (point))) ";")
       (backward-char)))

(defun c-esque-init ()
  (local-set-key "{" 'insert-brackets)
  (flyspell-prog-mode)
  (auto-fill-mode)
  (local-set-key [end] 'c-esque/end-of-line))

(add-hook 'c-mode-common-hook 'c-esque-init)